##
# Site settings
title:              Nick McCrea
url:                https://www.nickmccrea.com  # the base hostname & protocol for your site, e.g. http://example.com
baseurl:            ""                          # the subpath of your site, e.g. /blog
timezone:           America/New York
email:              nick@nickmccrea.com
phone:              305.602.4300
description: >
  Computer Engineering and Software Development in Miami, FL, USA.
author:             Nick McCrea

##
# Associated accounts
github_username:    nmccrea
linkedin_username:  nickmccrea
disqus:
  shortname:        nick-mccrea-blog
google_analytics:   UA-82093601-2

##
# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap  # This must appear AFTER all gems that create content that is to be mapped, and BEFORE gems that create content that is not to be mapped.

##
# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

##
# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock